### ISSUE TITLE
Vendor interface: Intera SDK

### ISSUE THREAD

**Issue by awesome-manuel** [fzi-forschungszentrum-informatik/fzi_robot_interface_proposal#13]
The Intera SDK from Rethink Robotics also has a cartesian interface called "MotionInterface": https://sdk.rethinkrobotics.com/intera/Motion_Interface_Tutorial

This should be considered as well in the vendor overview.

**Comment by fmauch** [comment]
Thanks for noting. Would you be willing to contribute a chapter about this vendor? That would probably be quicker and better than if we dig into the interface first.

**Comment by awesome-manuel** [comment]
Would you rather include it in the section "Existing Cartesian Interfaces in ROS" or "Vendor interfaces for Cartesian motions"? The Sawyer robot actually only provides a ROS native interface, having the ros master inside the robot itself.

**Comment by fmauch** [comment]
As we put the Doosan interface also into the "Vendor interfaces" section, I'd go that way. But I agree that it also should be mentioned in the ROS section.

I don't feel like being able to give a proper answer, let me have a look into it tomorrow!
