### ISSUE TITLE
Suggestion: drop wrench from CartesianTrajectoryPoint

### ISSUE THREAD

**Issue by gavanderhoorn** [fzi-forschungszentrum-informatik/fzi_robot_interface_proposal#2]
I know it's part of the messages I made available (and I believe there is one more), but I'm not convinced (not sure I ever was) about the inclusion of the `wrench` field in `CartesianTrajectoryPoint`.

Force/impedance control is certainly important, but perhaps it deserves its own message set (there are a few actually, [majorana](https://github.com/ros-industrial-consortium/majorana) being one of them). Those messages are typically much more complex than just a `Wrench`.

The current proposal seems to focus on position control with associated velocity and acceleration constraints. `Wrench` seems out-of-place there.

**Comment by fmauch** [comment]
My initial idea was to incude it in similarity to joint efforts. However, I understand that this analogy isn't 100% correct.

**Comment by gavanderhoorn** [comment]
Yeah, I figured it was there for symmetry reasons.
