### ISSUE TITLE
Some comments on the proposed posture structure

### ISSUE THREAD

**Issue by gavanderhoorn** [fzi-forschungszentrum-informatik/fzi_robot_interface_proposal#5]
The proposal text already acknowledges there are some things to hash out:

 1. should the field be made optional?
 1. should partial posture specifications be supported?

Personally, I would add:

 3. should `postures` be made a member of `CartesianTrajectoryPoint`?
 1. should `posture_joint_names` be a member of `CartesianPosture`?

As to the questions raised in the text:

> should the field be made optional?

My vote would be: yes. One could imagine kinematic structures for which only a single IK solution exists for a specific pose, or there are external constraints or guides which should determine which solutions should be used or is preferable. It could be that at the time of construction of the trajectory, it's *unknown* which pose would be "the best". Without `posture` being optional, it would be impossible to encode these cases correctly with this message.

> should partial posture specifications be supported?

Again: yes. The proposal text already mentions one benefit:

> It might be beneficial to allow partial posture definitions such as a shoulder lift joint or elbow joint value only

This same rationale was used for the `configuration` field in [vanderhoorn](https://fzi-robot-interface-proposal.readthedocs.io/en/latest/existing/09_vanderhoorn.html), and would support encoding posture/configuration information in the same way as many industrial robot controller do (mimicking the typical bitmask approach to specify turn numbers and up/down/flip/noflip/etc with joint angles).

Another reason to allow partial posture specification could be to support cases where IK solvers (or planners) are capable of optimising "the other" joints as part of searching for a solution, based on the set of joints which have been given an element in `posture`. This seems especially relevant when combined with `CartesianTolerance`.

The proposal continues with a disadvantage though:

> However, allowing this will require to have the joint names available at this stage, as well.

Which is a question I also had:

> should `posture_joint_names` be a member of `CartesianPosture`?

The text doesn't mention it, but I guess the rationale for not doing this was to avoid repeating the same information (ie: joint names) in every `CartesianPosture`. This would probably be a similar rationale behind the fact that a [JointTrajectory](http://docs.ros.org/melodic/api/trajectory_msgs/html/msg/JointTrajectory.html) has the `joint_names` field at the level of the `JointTrajectory` and not in each `JointTrajectoryPoint` (this is an assumption by me). This ultimately seems like an optimisation (ie: less data to transmit).

However, to support encoding partial postures, it would seem to be required to make `posture_joint_names` a member of `CartesianPosture`. As I feel it's important to support partial posture definitions, I would suggest to therefore extend `CartesianPosture` with a `joint_names` field.

> should `postures` be made a member of `CartesianTrajectoryPoint`?

The current proposal keeps `postures` as a member of `CartesianTrajectory`.  It's not made explicit, but perhaps this was done to keep `CartesianTrajectoryPoint` a *pure geometric representation of a setpoint independent of any robot configuration*. It does lead to this requirement:

>  The user has to make sure that the number of entries given in the `posture` array match the number of joints similar to the [trajectory_msgs/JointTrajectoryPoint](http://docs.ros.org/melodic/api/trajectory_msgs/html/msg/JointTrajectoryPoint.html) message.

I would probably suggest to give each `CartesianTrajectoryPoint` a `posture` member and remove the `postures` array at the `CartesianTrajectory` level. The main rationale being there is already a requirement for each traj pt to have a corresponding element in `postures`, and being a member makes that a) immediately clear, and b) easy to enforce (without needing additional code).

I believe it also helps facilitate optional posture support: users could assume *not* adding an element to `postures` would be interpreted as there no being a required posture (makes sense right:  "if you don't need it: don't add it to the array" could be the reasoning). But there is a requirement, due to the 1-to-1 matching mentioned earlier. So poses with no posture would be encoded with their `CartesianPosture` message being empty (ie: no names, empty `joint_values`).

**Comment by fmauch** [comment]
> The current proposal keeps postures as a member of CartesianTrajectory. It's not made explicit, but perhaps this was done to keep CartesianTrajectoryPoint a pure geometric representation of a setpoint independent of any robot configuration. 

Exactly. You elaborated quite well why the changes you suggested do make sense, though. I'll try to include your thoughts into the proposal and maybe come back with things to discuss :-)

**Edit:** Now I do remember my reasoning (which I did not write down explicitly, yes).

The idea of keeping the `CartesianTrajectoryPoint` clean of any robot posture is that this way it is reusable with another robot. In the end, a series of `CartesianTrajectoryPoint` would only define a sequence of tool poses in Cartesian space. Mapping them to an existing hardware configuration either by solving the IK or by commanding it to the robot directly would be done at execution / planning time.

By separating this we can save a Cartesian trajectory (in terms of its geometric representation) and decide at execution time about the parameters that should be used to execute it (posture, actual controlled frame tolerances, etc.)

However, I also see the point of the 1-to-1 mapping you mentioned. One could argue, that when reusing saved trajectories one would probably create a trajectory representation from a saved structure, anyway...

**Comment by fmauch** [comment]
@gavanderhoorn Would you agree with the changes proposed in #9?

**Comment by gavanderhoorn** [comment]
Re-reading this:

> The idea of keeping the `CartesianTrajectoryPoint` clean of any robot posture is that this way it is reusable with another robot. In the end, a series of `CartesianTrajectoryPoint` would only define a sequence of tool poses in Cartesian space. Mapping them to an existing hardware configuration either by solving the IK or by commanding it to the robot directly would be done at execution / planning time.
> 
> By separating this we can save a Cartesian trajectory (in terms of its geometric representation) and decide at execution time about the parameters that should be used to execute it (posture, actual controlled frame tolerances, etc.)

that rationale actually makes a lot of sense and I was going to suggest to *undo* whatever I had suggested should be changed.

But, then I wondered whether we're not conflating two things here:

 1. a tool path (which is a list of Cartesian poses with a certain origin)
 1. a robot trajectory -- which happens to be specified in Cartesian space

The first seems to be what you describe in your added rationale: a robot, and configuration agnostic list of Cartesian poses, which unambiguously describes a set of positions and rotations.

The second would then be the mapping of that list to a "representation" (if you will) of that set of poses which is achievable/reachable by a specific mechanism with a specific kinematic configuration. This latter form absolutely needs more information than just a list of Cartesian poses and will be robot-specific. Otherwise there are too many ambiguities to be able to properly execute the motions required to reach those poses.

Compare this to a `JointTrajectory`: yes, you could execute a `JointTrajectory` "for" one robot on another, and it would move, but looking at other aspects (such as the Cartesian poses the EEF might take) it would most likely not result in the same motions as the "other" robot. And that's even ignoring the dynamic aspects.

"Re-using" a trajectory in that sense doesn't really make sense to me.

We can certainly re-use a list of Cartesian target poses, but that would not be a trajectory.

**Comment by gavanderhoorn** [comment]
I realise you write

> By separating this we can save a Cartesian trajectory (in terms of its geometric representation) and decide at execution time about the parameters that should be used to execute it (posture, actual controlled frame tolerances, etc.)

which sounds like what I also say (but then with more words).

What I forgot to add is probably that I'd be OK with the coupling you appear to have liked to avoid (between the poses and the configurations), as a CartesianTrajectory is by definition specific to a particular robot / kinematic configuration.

So the coupling is acceptable, as imo we should not be using a trajectory to store a tool path.

**Comment by fmauch** [comment]
Closing this as from my point of view this has been covered in #15
