### ISSUE TITLE
Suggestion: describe the use-cases for which CartesianTrajectory is being designed

### ISSUE THREAD

**Issue by gavanderhoorn** [fzi-forschungszentrum-informatik/fzi_robot_interface_proposal#6]
The proposal includes a brief description of the [motivation](https://fzi-robot-interface-proposal.readthedocs.io/en/latest/introduction/index.html#target-of-this-project) but the use-cases which have led to the [requirements](https://fzi-robot-interface-proposal.readthedocs.io/en/latest/introduction/index.html#requirements) are not described.

It would be beneficial to include those, as it would give more insight into the rationale of the design decisions which have led to the current proposal.

Additionally, it would allow to declare some usages as out-of-scope, which could help keep the discussion on-topic.

**Comment by gavanderhoorn** [comment]
Ping?

**Comment by fmauch** [comment]
It's been 17 days already? I certainly do agree but haven't found the time for this, yet.

**Comment by fmauch** [comment]
Closing this as #8 got merged by now.
